plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.8'
    id 'io.spring.dependency-management' version '1.0.15.RELEASE'
}

group 'org.example'
version 'unspecified'

repositories {
    mavenCentral()
}

dependencies {

    implementation  project(":chiffrement-utils")

    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
    implementation group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5'

    /////////////// communication to nodejs front end ///////////////

}


test {
    useJUnitPlatform()
}