server.port=8092
logging.level.org.springframework=OFF
logging.level.root=OFF
spring.main.banner-mode=off


spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=POST,GET,PUT,DELETE
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true