plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.8'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'application'
}


application {
    mainClass = 'blockChain.ConsensusSpringApplication'
}


group = 'block-chain'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url 'https://maven.pkg.github.com/rsocket/rsocket-java' } // equivalent socket IO
    maven { url 'https://repo.spring.io/snapshot' }
}

dependencies {

    implementation project(path: ':vendor-bundle')
    implementation project(path: ':chiffrement-utils')
    // implementation project(path: ':wallet')

    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'


    implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
    implementation group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5'



}
